baseurl = "http://www.drembaru.de/"
languageCode = "en-us"
title = "drembaru"
theme = "vienna"

author = "Keichi Takahashi"
description = "Simple and clean blog theme for hugo"
license = "MIT"
name = "vienna"
source_repo = "git@github.com:keichi/vienna.git"
tags = ["blog", "tags", "bootstrap"]

[permalinks]
    post = "/:year/:month/:title/"

[params]
    themecolor = "green"
    image = "/img/pyrenees.jpg"
    subtitle = ""
    blogheader = "<span>drem<b>baru</b></span>"

[menu]
    [[menu.nav]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 0

    # [[menu.nav]]
    # identifier = "blog"
    # name = "Blog"
    # url = "/"
    # weight = 1

    [[menu.nav]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 2

    [[menu.nav]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact"
    weight     = 3
